language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t snehalshinde9227/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true snehalshinde9227/docker-react npm run test -- --coverage