language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t snehalshinde9227/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true snehalshinde9227/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-125343100861"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY